#!/bin/sh
#
# Load USB gadget modules
#

case "$1" in
  start)
	printf "Loading USB ethernet modules: "
	modprobe dwc2
	modprobe g_ether
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Unloading USB ethernet modules: "
	modprobe -r g_ether
	modprobe -r dwc2
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
 
